### ISSUE TITLE
Como proyecto necesito caso de uso extendido

### ISSUE THREAD

**Issue by mauriciocuervo** [maemarket/Mae-Market#7]

**Comment by esteban1000350620** [comment]
docs: se agrega casos de uso extendidos
[Casos de Uso formato extendido.docx](https://github.com/maemarket/Mae-Market/files/6274605/Casos.de.Uso.formato.extendido.docx)

**Comment by esteban1000350620** [comment]
docs: se agrega casos de uso extendidos
[Casos de Uso formato extendido.docx](https://github.com/maemarket/Mae-Market/files/6274605/Casos.de.Uso.formato.extendido.docx)
